### ISSUE TITLE
Cookie banner bliver ikke fjernet efter man har trykket "OK" i IE 11

### ISSUE THREAD

**Issue by jhof-nc** [CookiePrompter/CookiePrompter#4]
Hej

Vi, Tilbudsportalen.dk, oplever, at cookie banner container ikke bliver fjernet efter man har trykket "OK" i IE 11. 

Jeg har lagt mærke til, at cookie banner fungerer fint på https://erhvervsstyrelsen.dk/. Hvis jeg skulle gætte, hvorfor det ikke virker hos os, er det fordi vores design er baseret på designsystem.dk

div med class eksCookieContainer er usynligt på siden hos os, når man bruger dev tools, men ikke hos https://erhvervsstyrelsen.dk/.

Der kommer følgende fejl i logfilen af client:
SCRIPT438: Object doesn't support property or method 'remove'
index (1,8088)

Vi bruger Cookie Promper 2.2.2 minified version.

Tak for hjælpen.

**Comment by jhof-nc** [comment]
Hej

Vi har fået rettet fejlen på vores side ved brug af følgende Polyfill: https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove#Polyfill

Det ville stadig være godt at rette fejlen på jeres side, så man ikke er afhængig af Polyfill. Det viser sig, at remove metode ikke er understøttet af IE 11.

**Comment by dalager** [comment]
Hej Jonas
Tak for den 👍  -- jeg har fixet i release 2.3.2 :)
/christian #
